export const markets = {
  ar: 'Argentina',
  au: 'Australia',
  at: 'Austria',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  be: 'Belgium',
  bm: 'Bermuda',
  bw: 'Botswana',
  br: 'Brazil',
  bg: 'Bulgaria',
  ca: 'Canada',
  cl: 'Chile',
  cn: 'China',
  co: 'Colombia',
  hr: 'Croatia',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  dk: 'Denmark',
  eg: 'Egypt',
  ee: 'Estonia',
  fi: 'Finland',
  fr: 'France',
  de: 'Germany',
  gh: 'Ghana',
  gr: 'Greece',
  hk: 'Hong Kong',
  hu: 'Hungary',
  is: 'Iceland',
  in: 'India',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  it: 'Italy',
  ci: 'Ivory Coast',
  jm: 'Jamaica',
  jp: 'Japan',
  jo: 'Jordan',
  kz: 'Kazakhstan',
  ke: 'Kenya',
  kw: 'Kuwait',
  lv: 'Latvia',
  lb: 'Lebanon',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  mw: 'Malawi',
  my: 'Malaysia',
  mt: 'Malta',
  mu: 'Mauritius',
  mx: 'Mexico',
  ma: 'Morocco',
  na: 'Namibia',
  nl: 'Netherlands',
  nz: 'New Zealand',
  ng: 'Nigeria',
  no: 'Norway',
  om: 'Oman',
  pk: 'Pakistan',
  ps: 'Palestinian Authority',
  pe: 'Peru',
  ph: 'Philippines',
  pl: 'Poland',
  pt: 'Portugal',
  qa: 'Qatar',
  ro: 'Romania',
  ru: 'Russia',
  sa: 'Saudi Arabia',
  rs: 'Serbia',
  sg: 'Singapore',
  sk: 'Slovakia',
  si: 'Slovenia',
  za: 'South Africa',
  kr: 'South Korea',
  es: 'Spain',
  lk: 'Sri Lanka',
  se: 'Sweden',
  ch: 'Switzerland',
  tw: 'Taiwan',
  tz: 'Tanzania',
  th: 'Thailand',
  tt: 'Trinidad & Tobago',
  tn: 'Tunisia',
  tr: 'Turkey',
  ug: 'Uganda',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  gb: 'United Kingdom',
  us: 'United States',
  ve: 'Venezuela',
  vn: 'Vietnam',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};

export const endpoint =
  'https://api.simplywall.st/api/grid/filter?include=info,score';

export const pageSize = 24;
